trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:

  # ─────────────────────────────────────────────
  # STAGE 1 - Testes E2E
  # ─────────────────────────────────────────────
  - stage: Testes_E2E
    displayName: '🖥️ Testes E2E'
    jobs:
      - job: CypressE2E
        displayName: 'Executar Testes E2E'
        steps:

          - task: NodeTool@0
            displayName: '🟢 Configurar Node.js 18'
            inputs:
              versionSpec: '18.x'

          - script: npm ci
            displayName: '📦 Instalar dependências'

          - script: npx cypress run --env allure=true --spec "cypress/e2e/login.cy.js,cypress/e2e/inventory.cy.js,cypress/e2e/cart.cy.js,cypress/e2e/checkout.cy.js,cypress/e2e/menu.cy.js"
            displayName: '🧪 Executar testes E2E'
            continueOnError: true

          - script: npx allure generate allure-results --clean -o allure-report
            displayName: '📊 Gerar relatório Allure'
            condition: always()

          - task: PublishBuildArtifacts@1
            displayName: '📤 Publicar relatório Allure (E2E)'
            condition: always()
            inputs:
              pathToPublish: 'allure-report'
              artifactName: 'allure-report-e2e'

          - task: PublishBuildArtifacts@1
            displayName: '📤 Publicar screenshots (falhas)'
            condition: failed()
            inputs:
              pathToPublish: 'cypress/screenshots'
              artifactName: 'screenshots-e2e'

  # ─────────────────────────────────────────────
  # STAGE 2 - Testes de API
  # ─────────────────────────────────────────────
  - stage: Testes_API
    displayName: '🔌 Testes de API'
    dependsOn: []
    jobs:
      - job: CypressAPI
        displayName: 'Executar Testes de API'
        steps:

          - task: NodeTool@0
            displayName: '🟢 Configurar Node.js 18'
            inputs:
              versionSpec: '18.x'

          - script: npm ci
            displayName: '📦 Instalar dependências'

          - script: npx cypress run --env allure=true --spec "cypress/e2e/api/api.cy.js"
            displayName: '🔌 Executar testes de API'
            continueOnError: true

          - script: npx allure generate allure-results --clean -o allure-report
            displayName: '📊 Gerar relatório Allure'
            condition: always()

          - task: PublishBuildArtifacts@1
            displayName: '📤 Publicar relatório Allure (API)'
            condition: always()
            inputs:
              pathToPublish: 'allure-report'
              artifactName: 'allure-report-api'

          - task: PublishBuildArtifacts@1
            displayName: '📤 Publicar screenshots (falhas)'
            condition: failed()
            inputs:
              pathToPublish: 'cypress/screenshots'
              artifactName: 'screenshots-api'